apiVersion: apps/v1
kind: Deployment
metadata:
  name: codeguru-java-app-deployment-with-issues
  labels:
    app: codeguru-demo-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: codeguru-demo-app
  template:
    metadata:
      labels:
        app: codeguru-demo-app
    spec:
      serviceAccountName: codeguru-profiler
      containers:
      - name: codeguru-java-app-deployment-with-issues
        image: 338918620411.dkr.ecr.eu-west-1.amazonaws.com/codeguru-java-app-deployment-with-issues:latest
